// Textos visibles de la UI, centralizados (regla de oro: nada de strings sueltos).
// Todo en español; los identificadores quedan en inglés.

export const labels = {
  brand: 'Wintech AR',
  brandSub: 'Stock & Importaciones',
  searchPlaceholder: 'Buscar o ejecutar…',
  searchHint: 'Búsqueda global y paleta de comandos (Ctrl K)',
  notifications: 'Notificaciones',
  userName: 'Lucas P.',
  userRole: 'Dueño',
  footerNote: 'App de escritorio · datos locales · offline',

  comingSoon: 'Próximamente',
  comingSoonBody:
    'Esta pantalla forma parte del diseño y se implementará en una fase próxima. Ver el roadmap en docs/08.',

  products: {
    title: 'Productos',
    lede: 'Catálogo de perfiles, herrajes y accesorios. Alta, baja y modificación.',
    nuevo: 'Nuevo producto',
    buscar: 'Buscar por SKU o nombre…',
    vacioTitulo: 'Todavía no hay productos',
    vacioBody: 'Cargá tu primer producto con el botón "Nuevo producto", o importá tu catálogo.',
    sinResultados: 'Ningún producto coincide con la búsqueda.',
    editar: 'Editar',
    activar: 'Activar',
    desactivar: 'Desactivar',
    nuevoTitulo: 'Nuevo producto',
    editarTitulo: 'Editar producto',
    guardar: 'Guardar',
    cancelar: 'Cancelar',
    // Familias
    famTodas: 'Todas',
    famPerfil: 'Perfiles',
    famHerraje: 'Herrajes',
    famAccesorio: 'Accesorios',
    // Columnas
    colProducto: 'Producto',
    colFamilia: 'Familia',
    colMarca: 'Marca',
    colProveedor: 'Proveedor',
    colUnidad: 'Unidad',
    colCosto: 'Costo USD',
    colPrecio: 'Precio ARS',
    colMinimo: 'Mínimo',
    colEstado: 'Estado',
    colAcciones: '',
    activo: 'Activo',
    inactivo: 'Inactivo',
    // Campos del formulario
    fSku: 'SKU',
    fNombre: 'Nombre',
    fFamilia: 'Familia',
    fLinea: 'Línea',
    fColor: 'Color',
    fMarca: 'Marca',
    fProveedor: 'Proveedor',
    fUnidad: 'Unidad de venta',
    fLargoBarra: 'Largo de barra (m)',
    fPeso: 'Peso unitario (kg)',
    fVolumen: 'Volumen unitario (m³)',
    fCosto: 'Último costo (USD)',
    fPrecio: 'Precio de venta (ARS)',
    fMargen: 'Margen objetivo (%)',
    fMinimo: 'Stock mínimo',
    fSeguridad: 'Stock de seguridad',
    fObjetivo: 'Stock objetivo',
    fLeadTime: 'Lead time (días)',
    fActivo: 'Activo',
    secClasificacion: 'Clasificación',
    secComercial: 'Costos y precios',
    secStock: 'Stock y reposición',
    optSinMarca: '— Sin marca —',
    optSinProveedor: '— Sin proveedor —',
  },
};
